version: '3.8'

services:
  # Server
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  # App
  recommender:
    build: .
    container_name: movie_recommender
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434 
    stdin_open: true 
    tty: true

volumes:
  ollama_data: